# Argo CD'de yaratıldığında argocd-bootstrap repo'sundaki applicaton tanımlarını oluşturur.
# Oluşan application tanımları example-app ve example-app-2 repo'larını deploy eder.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app-of-apps
  namespace: argocd 
spec:
  project: default
  source:
    repoURL: https://github.com/mthnmdn/kustomize.git
    targetRevision: HEAD 
    path: argocd-bootstrap
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      enabled: true
